import type { CatalogItem } from '@/types';

// Server-side only — filenames inside private-images/, never sent to the client
export const LOCAL_IMAGES: Record<string, string> = {
  'pdf-scholar':       'pdf-scholar.png',
  'starry-scribe':     'starry-scribe.png',
  'cloud-shepherd':    'cloud-shepherd.svg',
  'digital-harvest':   'digital-harvest.svg',
  'lone-developer':    'lone-developer.svg',
  'open-source-fields':'open-source-fields.svg',
  'data-stream':       'data-stream.svg',
  'encrypted-garden':  'encrypted-garden.svg',
  'the-repository':    'the-repository.svg',
  'bandwidth-dusk':    'bandwidth-dusk.svg',
  'debug-hour':        'debug-hour.svg',
  'version-tree':      'version-tree.svg',
  'the-sprint':        'the-sprint.svg',
  'infinite-loop':     'infinite-loop.svg',
  'the-merge':         'the-merge.svg',
  'zero-day-dawn':     'zero-day-dawn.svg',
  'the-stack':         'the-stack.svg',
  'async-night':       'async-night.svg',
  'pull-request':      'pull-request.svg',
  'runtime-glow':      'runtime-glow.svg',
  'the-pipeline':      'the-pipeline.svg',
  'legacy-code':       'legacy-code.svg',
};

export const CATALOG: CatalogItem[] = [
  {
    id: 'pdf-scholar',
    title: 'The PDF Scholar',
    year: 2026,
    description: 'A Van Gogh-style portrait of a scholar bathed in lamplight, the promise of the Portable Document Format immortalized in oil and impasto — built for reliability, designed for the future.',
    vibe: ['scholarly', 'timeless', 'luminous'],
    price: 0.01,
    mimeType: 'image/png',
  },
  {
    id: 'starry-scribe',
    title: 'The Starry Scribe',
    year: 2026,
    description: 'Against a swirling Starry Night sky, a writer commits the eternal truth to paper: one file, any platform, every time. Van Gogh\'s cosmos as a testament to universal creation.',
    vibe: ['cosmic', 'creative', 'universal'],
    price: 0.01,
    mimeType: 'image/png',
  },
  {
    id: 'cloud-shepherd',
    title: 'The Cloud Shepherd',
    year: 2026,
    description: 'A lone shepherd tends to data clouds drifting through a midnight blue sky — every cloud a floating archive of the infinite.',
    vibe: ['pastoral', 'boundless', 'serene'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'digital-harvest',
    title: 'Digital Harvest',
    year: 2026,
    description: 'Golden data ripens under an emerald sky. Van Gogh paints the season of abundance — the harvest of ten thousand datasets.',
    vibe: ['golden', 'abundant', 'warm'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'lone-developer',
    title: 'The Lone Developer',
    year: 2026,
    description: 'At 3am, a solitary figure bathed in the cold blue glow of a monitor. Van Gogh captures the sacred loneliness of creation — the most exclusive piece in the collection.',
    vibe: ['intense', 'solitary', 'electric'],
    price: 0.02,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'open-source-fields',
    title: 'Open Source Fields',
    year: 2026,
    description: 'Rolling fields of freely shared code bloom beneath a collaborative sky — Van Gogh\'s brushstrokes celebrate the gift of open knowledge.',
    vibe: ['vibrant', 'communal', 'joyful'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'data-stream',
    title: 'Data Stream',
    year: 2026,
    description: 'Packets of meaning surge through fiber and air — Van Gogh\'s swirling hand traces the invisible rivers of data that bind the world.',
    vibe: ['flowing', 'electric', 'mysterious'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'encrypted-garden',
    title: 'The Encrypted Garden',
    year: 2026,
    description: 'Behind every firewall blooms a secret garden — keys and ciphers rendered as flowers, each petal a promise of private meaning.',
    vibe: ['secretive', 'lush', 'protective'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'the-repository',
    title: 'The Repository',
    year: 2026,
    description: 'An amber library of every commit ever made — Van Gogh illuminates the cathedral of version history, ancient scrolls of code preserved in amber.',
    vibe: ['ancient', 'warm', 'archival'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'bandwidth-dusk',
    title: 'Bandwidth at Dusk',
    year: 2026,
    description: 'The final packets stream home as the sun sets over the server farm — warm orange waves carry the last transmissions of the day.',
    vibe: ['nostalgic', 'warm', 'fading'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'debug-hour',
    title: 'The Debug Hour',
    year: 2026,
    description: 'The golden moment of clarity — a magnifying glass reveals the hidden flaw in a vast night of logic. Van Gogh captures the triumph of the found bug.',
    vibe: ['focused', 'triumphant', 'nocturnal'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'version-tree',
    title: 'The Version Tree',
    year: 2026,
    description: 'Every branch a feature, every leaf a commit — the version tree spreads against a forest sky, its roots deep in the first commit.',
    vibe: ['organic', 'branching', 'deep'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'the-sprint',
    title: 'The Sprint',
    year: 2026,
    description: 'Two weeks of furious motion — Van Gogh\'s burning strokes capture the velocity of a sprint: deadline looming, features flying, fire in every line.',
    vibe: ['urgent', 'fierce', 'blazing'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'infinite-loop',
    title: 'Infinite Loop',
    year: 2026,
    description: 'The program that forgot to stop — concentric ripples spreading into eternity, Van Gogh finds the strange peace inside the endless cycle.',
    vibe: ['meditative', 'endless', 'cool'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'the-merge',
    title: 'The Merge',
    year: 2026,
    description: 'Two branches converge in a sunset of resolution — Van Gogh witnesses the sacred moment when parallel work becomes one.',
    vibe: ['convergent', 'warm', 'resolved'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'zero-day-dawn',
    title: 'Zero Day Dawn',
    year: 2026,
    description: 'The rarest find — a vulnerability at first light, before anyone else knows. A crimson dawn breaks over the unknowing world.',
    vibe: ['rare', 'dawn', 'dangerous'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'the-stack',
    title: 'The Stack',
    year: 2026,
    description: 'Layer upon layer: OS, runtime, framework, application — Van Gogh paints the modern city of software rising against a slate sky.',
    vibe: ['architectural', 'layered', 'urban'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'async-night',
    title: 'Async/Await',
    year: 2026,
    description: 'The patient suspension — a promise floats in the cool dark, awaiting resolution. Van Gogh paints the beauty of disciplined waiting.',
    vibe: ['patient', 'cool', 'suspended'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'pull-request',
    title: 'Pull Request',
    year: 2026,
    description: 'A hand extended across the codebase — the pull request is an act of trust, a flower offered between collaborators.',
    vibe: ['collaborative', 'hopeful', 'gentle'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'runtime-glow',
    title: 'Runtime Glow',
    year: 2026,
    description: 'The moment the process starts — electric light floods outward as computation begins, Van Gogh\'s sun born again in silicon.',
    vibe: ['electric', 'energetic', 'born'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'the-pipeline',
    title: 'The Pipeline',
    year: 2026,
    description: 'Code flows from commit to deploy through the blue arteries of automation — Van Gogh paints the industrial river of continuous delivery.',
    vibe: ['industrial', 'flowing', 'reliable'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
  {
    id: 'legacy-code',
    title: 'Legacy Code',
    year: 2026,
    description: 'Ancient incantations written before memory — the amber light of old code still runs, still matters. Van Gogh honors what should not be touched.',
    vibe: ['ancient', 'amber', 'enduring'],
    price: 0.01,
    mimeType: 'image/svg+xml',
  },
];
